### ISSUE TITLE
Unable to make requests from client to api

### ISSUE THREAD

**Issue by link00000000** [Scribble-Editor/Scribble#73]
Requests blocked by CORS. All endpoints pertaining to the account/* route must allow CORS.

Possible resources:
- Django rest framework documentation: https://www.django-rest-framework.org/topics/ajax-csrf-cors/
- Repository recommended by rest framework documentation: https://github.com/adamchainz/django-cors-headers

**Comment by PatrickHoward** [comment]
Recloning seems to fix it ??
